jobs:
  include:
    - os: linux
      name: Ubuntu 18.04
      dist: bionic

# sudo: false
# addons:
  # apt:
    # packages:
      # # - libstdc++6
      # - fonts-droid

env:
  - CODECOV_TOKEN="4bd60378-87f7-4406-9335-31033252a2ac"

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter pub get

script:
  - ./flutter/bin/flutter test --coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

cache:
  directories:
    - $HOME/.pub-cache
